### PR TITLE
More fixes for gnome-shell 3.32.

### PR DESCRIPTION
**Pull request by jenslody**
Some whitespace removals have slipped in.

### CODE REVIEW

**Comment by thilomaurer** [comment]
Thanks for the PR.
I can see that it modernizes the implementation, but which specific thing is being fixed here?

**Comment by jenslody** [comment]
Sorry for not being more specific in my comment.
It simply does not start on Fedora with Gnome Shell Version 3.32.2 anymore.
Fedora mostly uses bleeding edge gnome (at least in test-updates repos).
Error message in journal is:
`Extension "pwcalc@thilomaurer.de" had error: TypeError: this._construct is not a function`
I did not test backwards compatibility.

**Comment by thilomaurer** [comment]
Verified that the changes run fine with 3.32.1 and 3.32.2 (Fedora 30) and 3.32.0 (Ubuntu 19.04.0)

**Comment by thilomaurer** [comment]
Uploaded (along other changes) to extensions.gnome.org: Review in progress.

**Pull request merged**
